server:
  port: ${TASK_TRACKER_BACKEND_PORT}
jwt:
  secret: ${JWT_SECRET}
  lifetime: 300m
spring:
  application:
    name: task-tracker-backend-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: 'classpath:db/changelog/db.changelog-master.xml'
    default-schema: 'public'

task-tracker-frontend:
  url: ${FRONTEND_URL}